### PR TITLE
✨ Fix MaPharma time

### LINKED ISSUE #102: Time with `mapharma.fr` is not correct
Time is not correct when a center is from `mapharma`.

Example:
image

```json
    {
      "departement": "49",
      "nom": "Pharmacie Des Halles",
      "url": "https://mapharma.net/49100-7?c=237&l=0",
      "location": {
        "longitude": -0.554808,
        "latitude": 47.47116,
        "city": "ANGERS"
      },
      "metadata": {
        "address": "78 RUE BAUDRIERE, 49100 ANGERS",
        "business_hours": null
      },
      "prochain_rdv": "2021-05-10T10:30:00",
      "plateforme": "Mapharma",
      "type": "drugstore",
      "appointment_count": 19,
      "internal_id": "mapharma2d373f633d323337266c3d3",
      "vaccine_type": [
        "AstraZeneca"
      ],
      "appointment_by_phone_only": false,
      "erreur": null,
      "last_scan_with_availabilities": "2021-05-08T17:17:29.605276+02:00",
      "appointment_schedules": {
        "1_days": 0,
        "2_days": 0,
        "7_days": 19,
        "28_days": 19,
        "49_days": 19
      },
      "gid": "2d373f633d323337266c3d3"
    }
```

Other source example:
```json
    {
      "departement": "49",
      "nom": "Centre de vaccination Covid-19 - Ville de Saumur",
      "url": "https://www.doctolib.fr/centre-de-sante/saumur/centre-de-vaccination-covid-19-ville-de-saumur",
      "location": {
        "longitude": -0.094039,
        "latitude": 47.267295,
        "city": "Saumur"
      },
      "metadata": {
        "address": "Avenue du Breil, 49400 Saumur",
        "phone_number": "+33241831288",
        "business_hours": {
          "lundi": "08:30-12:00, 13:30-17:00",
          "mardi": "08:30-12:00, 13:30-17:00",
          "mercredi": "08:30-12:00, 13:30-17:00",
          "jeudi": "08:30-12:00, 13:30-17:00",
          "vendredi": "08:30-12:00, 13:30-17:00",
          "samedi": null,
          "dimanche": null
        }
      },
      "prochain_rdv": "2021-05-11T10:10:00.000+02:00",
      "plateforme": "Doctolib",
      "type": "vaccination-center",
      "appointment_count": 1129,
      "internal_id": "doctolib242320",
      "vaccine_type": [
        "Pfizer-BioNTech",
        "Moderna"
      ],
      "appointment_by_phone_only": false,
      "erreur": null,
      "last_scan_with_availabilities": "2021-05-08T17:17:29.613270+02:00",
      "appointment_schedules": {
        "7_days": 33,
        "28_days": 658,
        "49_days": 1129,
        "1_days": 0,
        "2_days": 0
      },
      "gid": "d242320"
    }
```

### PR DESCRIPTION
**Pull request by NathanFallet**
Fix #102 

image

In the case of MaPharma.fr, the date is timezoned without timezone specified. So to fix this, I got the difference between Paris time and UTC/GTM time, to add it at the end of the timezoned date. (so it add `+02:00` or `+01:00` depending on summer or winter time)

Note: my first idea was to remove the `T` to parse it as a local date, but it would work only if user is in correct timezone.

### CODE REVIEW

**Review by PlugNPush — APPROVED** [review]

**Comment by NathanFallet** [comment]
@victor-sarda This fix is waiting to be merged for a month, and is quite important. It would take only two minutes to review it and merge it.

File: ViteMaDose/Helpers/Extensions/String+Commons.swift [hunk 1]
```diff
@@ -20,6 +20,13 @@ extension String {
     /// - Parameter region: custom option `Region`
     /// - Returns: optional `Date`
```
Comment (pylapp) [inline ViteMaDose/Helpers/Extensions/String+Commons.swift:21]: Returns optional of String, not Date

File: ViteMaDose/Helpers/Extensions/String+Commons.swift [hunk 2]
```diff
@@ -20,6 +20,13 @@ extension String {
     /// - Parameter region: custom option `Region`
```
Comment (pylapp) [inline ViteMaDose/Helpers/Extensions/String+Commons.swift:20]: Missing details for _style_ parameter

**Review by pylapp — CHANGES_REQUESTED** [review]

**Review by pylapp — APPROVED** [review]
